### ISSUE TITLE
changed ".br" to ".my" ---fail to run

### ISSUE THREAD

**Issue by tomsyaf** [paulodarosa/shopee-scrapper#1]
Exception has occurred: KeyError
'data'
  File "C:\Users\apit's Desktop\Documents\myCode\Shopee\scrape.py", line 17, in <module>
    num_ads = (r.json()['data']['sections'][0]['data']['item'])
               ~~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by paulodarosa** [comment]
Hi. How's it going, @tomsyaf?

Looks like Shopee uses a different API or endpoint to provide data to users based on Malaysia/or using the .my domain.

Since the script was made to provide data from the Brazilian market, I'm going to close this topic not as an issue, but I'll add this specific point in a future development.

I'll probably follow these steps:

1. Validate which API Shopee uses to deliver data to users based on Malaysia;
2. Check the seller's localition (using this specific API);
3. With steps 1 and 2 I can easily switch the end point inside the script, then it will scrap the data.

Thank you for opening this issue and letting me know about this.

**Comment by tomsyaf** [comment]
> Hi. How's it going, @tomsyaf?
> 
> Looks like Shopee uses a different API or endpoint to provide data to users based on Malaysia/or using the .my domain.
> 
> Since the script was made to provide data from the Brazilian market, I'm going to close this topic not as an issue, but I'll add this specific point in a future development.
> 
> I'll probably follow these steps:
> 
> 1. Validate which API Shopee uses to deliver data to users based on Malaysia;
> 2. Check the seller's localition (using this specific API);
> 3. With steps 1 and 2 I can easily switch the end point inside the script, then it will scrap the data.
> 
> Thank you for opening this issue and letting me know about this.

Thanks, i guess i can't use your code and get it to work then. lol
